name: 'AzureBicepDeploy'
 
on:
  push:
    branches:
    - main
  pull_request:
 
jobs:
 
  AzureBicepDeploy:
    name: 'AzureBicepDeploy'
    runs-on: ubuntu-latest
    env:
      ResourceGroupName: k8playground
      ResourceGroupLocation: "westus"
    environment: production
 
    steps:
 
    - uses: actions/checkout@v2
 
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
 
    - name: Azure Bicep Build
      run: |
        az bicep build --file IaC/bicep/main.bicep
      
    - name: Deploy Azure Bicep
      uses: Azure/arm-deploy@v1
      with:
        scope: subscription
        region: "westus"
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        template: ./IaC/bicep/main.json 