name: 'AzureBicepDeploy'
 
on:
  push:
    branches:
    - main
  pull_request:
 
jobs:
 
  AzureBicepDeploy:
    name: 'AzureBicepDeploy'
    runs-on: ubuntu-latest
    env:
      ResourceGroupName: k8playground
      ResourceGroupLocation: "westus"
    environment: production
 
    steps:
 
    - uses: actions/checkout@v2
 
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
 
    - name: Azure Bicep Build
      run: |
        az bicep build --file IaC/bicep/k8playground.bicep
 
    - name: Az CLI Create Resource Group
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}
 
    - name: Deploy Azure Bicep
      uses: Azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.ResourceGroupName }}
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        template: ./IaC/bicep/k8playground.json 